### ISSUE TITLE
Subname expiry does not display in manager app

### ISSUE THREAD

**Issue by tboeckmann** [ensdomains/ens-app-v3#493]
**Problem**
When I set an expiry on a subname, the expiry does not display in manager. 

Is the expiry correctly set?
Am I missing something?

**Details:**
`nachos.lovedaos.eth` has been [set to expire](https://etherscan.io/tx/0x48f6f24aca9fff7caa18a0506ad01784f244384f9e4403a2ef20261de9a41df0) on `1683102616` (the current time is `1683023981`).

Etherscan result for `0x2ed723f2e69d9b783e0b4912f8a2e258e72ab62f342fe6be77f4822cc1446a34` (nachos.lovedaos.eth)

```plaintext
id (uint256): 0x2ed723f2e69d9b783e0b4912f8a2e258e72ab62f342fe6be77f4822cc1446a34

[ getData(uint256) method Response ]
  owner   address :  [0xDC3c886D5b0528E9C99F66820f9F2409a2e8C2cA](https://etherscan.io/address/0xDC3c886D5b0528E9C99F66820f9F2409a2e8C2cA)
  fuses   uint32 :  262144
  expiry   uint64 :  1683102616
```
<img width="459" alt="image" src="https://user-images.githubusercontent.com/2022378/235645845-1de87319-8dc9-4f7c-b320-3ecc7e6d4403.png">

https://app.ens.domains/nachos.lovedaos.eth does not display the expiry date:
<img width="624" alt="image" src="https://user-images.githubusercontent.com/2022378/235645807-9ea78fb9-f406-4d2a-8648-25cb0d5a92e8.png">

**Comment by TateB** [comment]
if the PARENT_CANNOT_CONTROL fuse has not been burned on the name we don't show the expiry, since until it is burned the expiry doesn't mean anything. if you still want to view the expiry, you can see it in the `Permissions` tab
<img width="1028" alt="Screenshot 2023-06-20 at 10 22 22 am" src="https://github.com/ensdomains/ens-app-v3/assets/11844316/145dadeb-2c4b-4b6b-a04c-1b11d43093f1">
